"""Allow multiple Poynt businesses per user

Revision ID: 82fe428a4c70
Revises: 6d67031124e6
Create Date: 2026-08-27 19:56:53.206021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fe428a4c70'
down_revision: Union[str, Sequence[str], None] = '6d67031124e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poynt_connections_user_id'), table_name='poynt_connections')
    op.create_index(op.f('ix_poynt_connections_user_id'), 'poynt_connections', ['user_id'], unique=False)
    op.create_unique_constraint('uq_poynt_connection_user_business', 'poynt_connections', ['user_id', 'business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_poynt_connection_user_business', 'poynt_connections', type_='unique')
    op.drop_index(op.f('ix_poynt_connections_user_id'), table_name='poynt_connections')
    op.create_index(op.f('ix_poynt_connections_user_id'), 'poynt_connections', ['user_id'], unique=True)
    # ### end Alembic commands ###
